export const Agripreneurs = [
    {
        id: 1,
        image: "https://www.geotab.com/CMS-Media-production/AU/Solutions/Agribusiness/agribusiness-hero-banner-australia@2x.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 2,
        image: "https://media.istockphoto.com/id/506164764/photo/tractor-spraying-soybean-field.jpg?s=612x612&w=0&k=20&c=h27yHr07QNSghYS20iwYBCGjZIa2HlXqrZDkM0ZsYEw=",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 3,
        image: "https://wallpapers.com/images/featured/sustainable-agriculture-t1tte6fs05hrpkyc.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 4,
        image: "https://investorplace.com/wp-content/uploads/2020/06/agriculture-stocks.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 5,
        image: "https://investorplace.com/wp-content/uploads/2020/07/agriculturestocks1600-768x432.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 6,
        image: "https://t4.ftcdn.net/jpg/02/43/52/57/360_F_243525780_r8sdu06FUxVmqvf3YUthU5s9nE0z0lhh.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 7,
        image: "https://static.vecteezy.com/system/resources/previews/036/223/422/non_2x/ai-generated-rows-of-young-corn-plants-growing-on-the-field-generative-ai-photo.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
    {
        id: 8,
        image: "https://www.shutterstock.com/image-photo/agricultural-land-green-corn-farm-600nw-1934905055.jpg",
        title: "VGA Fish Farm",
        review: "91 Reviews",
        count: "56",
        address: "Ibeju Lekki, off Agugungi Road Lagos Nigeria",
        amount: "56m",
    },
]